@startuml
Client -> "Bank agent" : [[https://github.com/PawelJaworski/ddd-loan-application/blob/master/src/main/java/pl/javorek/ddd/service/applicationforloan/application/cmd/ApplicationForALoanCmdFacade.java#L24 Submit loan application]]
"Bank agent" --> "Client" : Loan application submitted
Client -> "Bank agent" : [[https://github.com/PawelJaworski/ddd-loan-application/blob/master/src/main/java/pl/javorek/ddd/service/applicationforloan/application/cmd/ApplicationForALoanCmdFacade.java#L38 Provide requred documents]]
"Bank agent" -> "Bank analyst" : [[https://github.com/PawelJaworski/ddd-loan-application/blob/master/src/main/java/pl/javorek/ddd/service/applicationforloan/application/cmd/ApplicationForALoanCmdFacade.java#L38 Send request for loan start]]
"Bank analyst" -> "Bank analyst" : Accept loan request
"Bank analyst" --> "Bank agent" : Loan started
"Bank agent" --> "Client" : Loan started communication sent
@enduml
