@startuml
autonumber
actor Client as client
actor       "Bank agent" as bankAgent
boundary    "Bank" as bank
client -> bankAgent : [[https://github.com/PawelJaworski/ddd-loan-application/blob/main/src/main/java/pl/javorek/ddd/service/applicationforloan/application/command/ApplicationForALoanCmdFacade.java Submit loan application]]
bankAgent --> client : Loan application submitted
client -> bankAgent : [[https://github.com/PawelJaworski/ddd-loan-application/blob/main/src/main/java/pl/javorek/ddd/service/applicationforloan/application/command/ApplicationForALoanCmdFacade.java Provide required documents]]
bankAgent -> bank : [[https://github.com/PawelJaworski/ddd-loan-application/blob/main/src/main/java/pl/javorek/ddd/service/applicationforloan/application/command/ApplicationForALoanCmdFacade.java Send request for loan start]]
bank -> bank : Accept loan request
bank --> bankAgent : Loan started
bankAgent --> client : Communication about started loan sent
@enduml
