@startuml
autonumber
actor Client as client
actor       "Bank agent" as bankAgent
boundary    "Bank" as bankAnalyst
client -> bankAgent : [[https://github.com/PawelJaworski/ddd-loan-application/blob/main/src/main/java/pl/javorek/ddd/service/applicationforloan/application/command/ApplicationForALoanCmdFacade.java Submit loan application]]
bankAgent --> client : Loan application submitted
client -> bankAgent : [[https://github.com/PawelJaworski/ddd-loan-application/blob/main/src/main/java/pl/javorek/ddd/service/applicationforloan/application/command/ApplicationForALoanCmdFacade.java Provide required documents]]
bankAgent -> bankAnalyst : [[https://github.com/PawelJaworski/ddd-loan-application/blob/main/src/main/java/pl/javorek/ddd/service/applicationforloan/application/command/ApplicationForALoanCmdFacade.java Send request for loan start]]
bankAnalyst -> bankAnalyst : Accept loan request
bankAnalyst --> bankAgent : Loan started
bankAgent -> client : Send communication about started loan
@enduml
